server:
  port: 30000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/scaffold?serverTimezone=Hongkong&useSSL=false&useUnicode=true&characterEncoding=UTF-8&nullCatalogMeansCurrent=true
    hikari:
      username: root
      password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: mysql
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  redis:
    database: 2
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: -1
        # 连接池最大阻塞等待时间（使用负值表示没有限制
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
  rabbitmq:
    username: admin
    password: admin
    port: 5672
    host: 127.0.0.1


# swagger配置
swagger:
  enabled: true
  title: "API"
  base-package: top.bluebirds37.scaffold.controller
blue:
  auth:
    permit-url-list:
      - /swagger-ui.html
      - /webjars/**
      - /swagger-resources/**
      - /v2/**
      - /favicon.ico
      - /
      - /csrf
      - /error
